export const Cities = [
  { title: 'Paris', value: 'paris' },
  { title: 'London', value: 'london' },
  { title: 'New York', value: 'new york' },
  { title: 'Tokyo', value: 'tokyo' },
  { title: 'Rome', value: 'rome' },
  { title: 'Barcelona', value: 'barcelona' },
  { title: 'Dubai', value: 'dubai' },
  { title: 'Singapore', value: 'singapore' },
  { title: 'Bangkok', value: 'bangkok' },
  { title: 'Istanbul', value: 'istanbul' },
  { title: 'Hong Kong', value: 'hong kong' },
  { title: 'Sydney', value: 'sydney' },
  { title: 'Los Angeles', value: 'los angeles' },
  { title: 'Amsterdam', value: 'amsterdam' },
  { title: 'Berlin', value: 'berlin' },
  { title: 'Prague', value: 'prague' },
  { title: 'Vienna', value: 'vienna' },
  { title: 'Las Vegas', value: 'las vegas' },
  { title: 'Miami', value: 'miami' },
  { title: 'Venice', value: 'venice' },
  { title: 'Florence', value: 'florence' },
  { title: 'Madrid', value: 'madrid' },
  { title: 'Seoul', value: 'seoul' },
  { title: 'Beijing', value: 'beijing' },
  { title: 'Shanghai', value: 'shanghai' },
  { title: 'Rio de Janeiro', value: 'rio de janeiro' },
  { title: 'Cape Town', value: 'cape town' },
  { title: 'Toronto', value: 'toronto' },
  { title: 'Vancouver', value: 'vancouver' },
  { title: 'San Francisco', value: 'san francisco' },
  { title: 'Chicago', value: 'chicago' },
  { title: 'Washington DC', value: 'washington dc' },
  { title: 'Boston', value: 'boston' },
  { title: 'Dublin', value: 'dublin' },
  { title: 'Edinburgh', value: 'edinburgh' },
  { title: 'Athens', value: 'athens' },
  { title: 'Santorini', value: 'santorini' },
  { title: 'Lisbon', value: 'lisbon' },
  { title: 'Porto', value: 'porto' },
  { title: 'Budapest', value: 'budapest' },
  { title: 'Warsaw', value: 'warsaw' },
  { title: 'Krakow', value: 'krakow' },
  { title: 'Saint Petersburg', value: 'saint petersburg' },
  { title: 'Moscow', value: 'moscow' },
  { title: 'Marrakech', value: 'marrakech' },
  { title: 'Bali', value: 'bali' },
  { title: 'Phuket', value: 'phuket' },
  { title: 'Hanoi', value: 'hanoi' },
  { title: 'Ho Chi Minh City', value: 'ho chi minh city' },
  { title: 'Kyoto', value: 'kyoto' },
  { title: 'Osaka', value: 'osaka' },
] as const;
